# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

##################
# Docker
##################
alias dimg="docker images"
alias drmi="docker rmi"
alias dps="docker ps -a"
alias drm="docker rm"
alias dkill="docker kill"
alias dstart="docker start"
alias dstop="docker stop"
alias drestart="docker restart"
alias dpull="docker pull"
alias dpush="docker push"
alias dexec="docker exec"
alias dlogs="docker logs"
alias dstats="docker stats --format 'table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.MemPerc}}\t{{.NetIO}}\t{{.BlockIO}}\t{{.PIDs}}' --no-stream"
alias d-c="docker-compose"
alias d-m="docker-machine"

##################
# System
##################

# System update
update(){
    sudo apt update
    sudo apt full-upgrade -y
    sudo apt autoremove -y
}

# System update through proxychians4
pupdate(){
    sudo proxychains4 -q -f ~/.dotfiles/config/proxychains4.conf apt update
    sudo proxychains4 -q -f ~/.dotfiles/config/proxychains4.conf apt full-upgrade -y
    sudo apt autoremove -y
}

# Search software package
alias search="apt-cache search"

# Update hosts
alias hosts="sudo ~/.dotfiles/script/hosts.sh"

# System backup
alias sysnap="sudo snapper -c root"

# Apt fix
alias apt-fix="~/.dotfiles/script/apt-get-fix.sh"

# Instead rm command
alias trash="~/.dotfiles/script/trash.sh"
alias trash-clean="rm -rf ~/.local/share/Trash/files/*"

##################
# Software
##################

# Aria2
alias aria2="aria2c --conf-path=$HOME/.dotfiles/config/aria2.conf"
alias paria2="~/.dotfiles/script/proxychains4.sh aria2c --conf-path=$HOME/.dotfiles/config/aria2.conf"

# Proxychains4
alias spc4="sudo ~/.dotfiles/script/proxychains4.sh"
alias pc4="~/.dotfiles/script/proxychains4.sh"

# Terminal Proxy
alias set_proxy="~/.dotfiles/script/export_proxy.sh -s"
alias unset_proxy="~/.dotfiles/script/export_proxy.sh -u"

# Network
alias ntop="sudo nethogs"
alias iptraf="sudo iptraf -i all"

# GBK to utf-8
alias conv="~/.dotfiles/script/utf-gbk.sh"

# Git commit
alias gcommit="~/.dotfiles/script/git-commit.sh"

# Weather
alias weather="~/.dotfiles/script/weather.py"

# Git.io
alias giturl="~/.dotfiles/script/git.io.sh"

# Tmux
tmux_start(){
    if [[ -z "$TMUX" ]] ;then
        ID="`tmux ls | grep -vm1 attached | cut -d: -f1`" # get the id of a deattached session
        if [[ -z "$ID" ]] ;then # if not available create a new one
            tmux new-session
        else
            tmux attach-session -t "$ID" # if available attach to it
        fi
    fi
}
tmux_start
alias z="tmux_start"

##################
# ENV
##################

export EDITOR="vim"
# export http_proxy="socks5://127.0.0.1:1080"
# export https_proxy="socks5://127.0.0.1:1080"
