# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export TERM="xterm-256color"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE='nerdfont-complete'
#POWERLEVEL9K_COLOR_SCHEME='dark'

POWERLEVEL9K_CUSTOM_INTERNET_SIGNAL="zsh_internet_signal"
zsh_internet_signal(){
  # Try to ping google DNS to see if you have internet
  local net=$(ping 8.8.8.8 -c 1| grep transmitted | awk '{print $6}' | grep 0)
  local color='%F{red}'
  local symbol="\uf127"
  if [[ ! -z "$net" ]] ;
  then color='%F{green}' ; symbol="\uf1e6" ;
  fi

  echo -n "%{$color%}$symbol" # \f1eb is wifi bars
}

# 两行终端, 去掉分隔符号
#POWERLEVEL9K_PROMPT_ON_NEWLINE=true
# POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
# 行首修饰符号
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}%F{white}"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}%F{white} "
# 左右元素
# custom_internet_signal load ram_joined context
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context root_indicator dir dir_writable_joined vcs status)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time background_jobs_joined time_joined)
# 用户颜色
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="clear"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="blue"
# VCS颜色
#POWERLEVEL9K_SHOW_CHANGESET=true
#POWERLEVEL9K_CHANGESET_HASH_LENGTH=6
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="clear"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="clear"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="clear"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="green"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="red"
# 自己的目录颜色
POWERLEVEL9K_DIR_HOME_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_FOREGROUND="blue"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="blue"
# 不是自己的目录颜色
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="clear"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="red"
# 命令执行状态颜色
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_STATUS_OK_BACKGROUND="clear"
POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="clear"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
# 时间颜色
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M,%a,%m-%d}"
POWERLEVEL9K_TIME_BACKGROUND="clear"
POWERLEVEL9K_TIME_FOREGROUND="cyan"
# 执行时间颜色
#POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=5
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='clear'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='magenta'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='clear'
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='green'
# 硬件状态
POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND="clear"
POWERLEVEL9K_LOAD_WARNING_BACKGROUND="clear"
POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="clear"
POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND="249"
POWERLEVEL9K_LOAD_WARNING_FOREGROUND="249"
POWERLEVEL9K_LOAD_NORMAL_FOREGROUND="249"
POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="green"
POWERLEVEL9K_RAM_BACKGROUND="clear"
POWERLEVEL9K_RAM_FOREGROUND="249"
POWERLEVEL9K_RAM_ELEMENTS=(ram_free)

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

##################
# Docker
##################
alias dimg="docker images"
alias drmi="docker rmi"
alias dps="docker ps -a"
alias drm="docker rm"
alias dkill="docker kill"
alias dstart="docker start"
alias dstop="docker stop"
alias drestart="docker restart"
alias dpull="docker pull"
alias dpush="docker push"
alias dexec="docker exec"
alias dlogs="docker logs"
alias dstats="docker stats --format 'table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.MemPerc}}\t{{.NetIO}}\t{{.BlockIO}}\t{{.PIDs}}' --no-stream"
alias d-c="docker-compose"
alias d-m="docker-machine"

##################
# System
##################
alias update="apt update && apt full-upgrade -y && apt autoremove -y"
alias pupdate="proxychains4 -q apt update && proxychains4 -q apt full-upgrade -y && apt autoremove -y"
alias apt-fix="apt autoclean && apt clean && rm -rf /var/lib/apt/lists && mkdir -p lists/partial"
alias search="apt-cache search"
alias -g pc4="proxychains4 -q"

alias i="apt install"

alias shproxy="~/Sync/Shell/shproxy.sh"
alias pyhttp="python -m SimpleHTTPServer"
alias ntop="nethogs wlp2s0"
alias iptraf="iptraf -i all"

##################
# Personal Tools
##################
alias aria2="aria2c --conf-path=$HOME/apps/aria2c.conf"
alias paria2="$HOME/.dotfiles/scripts/proxychains4.sh aria2c --conf-path=$HOME/apps/aria2c.conf"
alias off="while true; do sleep 1; xset dpms force off; sleep 4; done"
alias color='for i in {0..255}; do printf "\x1b[38;5;${i}mcolour${i}\x1b[0m\n"; done'
alias hyper="$HOME/apps/hyper"
alias t="$HOME/.dotfiles/scripts/todo.sh"
alias -g btc="$HOME/.dotfiles/scripts/btc.sh"
alias rezsh="source ~/.zshrc && tput cnorm"
alias ws="cd $GOPATH/src"
alias gows="cd $GOPATH/src/github.com/izuolan"

# rec time log; play time log 2;
# script -t -q -a
alias rec="script -t -q 2> time.rec log.rec"
alias play="scriptreplay time.rec log.rec"

# Tmux
tmux_init() {
    tmux new-session -d -n "Deafult" #"~/Sync/Shell/btc.sh -u"
    # tmux new-window -n "Other"
    tmux split-window -hp 75 "~/Sync/Shell/btc.sh -e"
    tmux split-window -vp 50 -t 2
    tmux split-window -hp 50 -t 2 "vim ~/Sync/Shell/todo.md"
    tmux select-pane -t 4
    tmux -2 attach-session -d
}
tmux_start(){
    if [[ -z "$TMUX" ]] ;then
        ID="`tmux ls | grep -vm1 attached | cut -d: -f1`" # get the id of a deattached session
        if [[ -z "$ID" ]] ;then # if not available create a new one
            tmux #tmux_init
        else
            tmux attach-session -t "$ID" # if available attach to it
        fi
    fi
}
tmux_start
alias z="tmux_start"

# 文件名从GB转码
mvgb () {
  for i in $*; do
        new="`echo $i|iconv -f utf8 -t latin1|iconv -f gbk`"
        echo $new
        echo -n 'Sure? '
        read -q ans && mv -i $i $new
        echo
    done
}
# Blur effect in Konsole
#if [ `echo $DISPLAY` ]; then
#  konsolex=$(qdbus | grep konsole | cut -f 2 -d\ )
#  if [ -n konsolex ]; then
#    for konsole in $konsolex; do
#      xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id `qdbus $konsole /konsole/MainWindow_1 winId`;
#    done
#  fi
#fi
export EDITOR="vim"
#export http_proxy="http://127.0.0.1:8118"
#export https_proxy="http://127.0.0.1:8118"
